apiVersion: batch/v1
kind: CronJob
metadata:
  name: random-article
  namespace: dwk-project
spec:
  schedule: '0 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: random-article
              image: glassb3ad/random-article:1.1
              env:
                - name: URL
                  value: 'http://todo-backend:2346/tasks'
          restartPolicy: OnFailure
