apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: dwk-exercises-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-ping-pong
          persistentVolumeClaim:
            claimName: ping-pong-claim
        - name: config-volume
          configMap:
            name: log-output-configmap
      containers:
        - name: log-output
          image: glassb3ad/log-output:1.7
          volumeMounts:
            - name: config-volume
              mountPath: /config
          env:
            - name: PORT
              value: '3002'
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap
                  key: message
