apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ping-pong-claim
  namespace: dwk-exercises-namespace
spec:
  storageClassName: exercise-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
