apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  namespace: dwk-project
spec:
  type: ClusterIP
  selector:
    app: todo-backend
  ports:
    - port: 2346
      protocol: TCP
      targetPort: 3002
