apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml
images:
  - name: PROJECT/IMAGE
    newName: glassb3ad/project-v-1:1.6
