apiVersion: v1
kind: PersistentVolume
metadata:
  name: project-pv
spec:
  storageClassName: project-pv
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: my-persistent-disk
    fsType: ext4
