apiVersion: v1
kind: Service
metadata:
  name: project-v-1
  namespace: dwk-project
spec:
  type: NodePort
  selector:
    app: project-v-1
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3002
