apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: dwk-exercises-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: shared-ping-pong
          persistentVolumeClaim:
            claimName: ping-pong-claim
      containers:
        - name: ping-pong
          image: glassb3ad/ping-pong:1.4
          volumeMounts:
            - name: shared-ping-pong
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: '3003'
