apiVersion: v1
kind: Service
metadata:
  name: ping-pong
  namespace: dwk-exercises-namespace
spec:
  type: ClusterIP
  selector:
    app: ping-pong
  ports:
    - port: 2346
      protocol: TCP
      targetPort: 3003
