apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - psql-service.yaml
  - secret.yaml
  - statefulset.yaml
images:
  - name: PROJECT/IMAGE
    newName: glassb3ad/todo-backend:1.4
