apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  namespace: dwk-project
spec:
  type: NodePort
  selector:
    app: todo-backend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3003
