apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: dwk-exercises-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: glassb3ad/ping-pong:1.9
          env:
            - name: PORT
              value: '3000'
            - name: DB_HOST
              value: 'postgres-0.postgres-service'
            - name: DB_PORT
              value: '5432'
            - name: DB_USER
              value: 'pingpong'
            - name: DB_PASSWORD
              value: 'pingpongpassword'
            - name: DB_NAME
              value: 'pingpongdb'
