apiVersion: v1
kind: Service
metadata:
  name: ping-pong
  namespace: dwk-exercises-namespace
spec:
  type: LoadBalancer
  selector:
    app: ping-pong
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
